version: "3.9"
services:
  nextjs-grpc-infra-target-aws:
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - type: volume
        source: vscode-extensions
        target: /root/.vscode-server/extensions
      - type: volume
        source: vscode-extensions-insiders
        target: /root/.vscode-server-insiders/extensions
      - type: bind
        source: ~/.config/gh
        target: /home/terraform/.config/gh
        read_only: true
      - type: bind
        source: ~/.kube
        target: /home/terraform/.kube
      - type: volume
        source: go
        target: /go
      - type: bind
        source: ~/.aws/credentials
        target: /home/terraform/.aws/credentials
        read_only: true

volumes:
  vscode-extensions:
    name: nextjs-grpc-infra-target-aws-vscode-extensions
  vscode-extensions-insiders:
    name: nextjs-grpc-infra-target-aws-vscode-extensions-insiders
  go:
    name: nextjs-grpc-infra-target-aws-go
